# Generated by Django 3.2.9 on 2023-04-08 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_choice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 13, 47, 12, 332960), verbose_name='date-asked'),
        ),
    ]
