# Generated by Django 3.2.9 on 2023-04-11 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 10, 25, 5, 52452), verbose_name='date-asked'),
        ),
    ]
