# Generated by Django 3.2.9 on 2023-04-14 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_user'),
        ('poll', '0009_auto_20230414_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='voters',
            field=models.ManyToManyField(default=None, to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 1, 31, 34, 781639), verbose_name='date-asked'),
        ),
    ]
