# Generated by Django 3.2.9 on 2023-04-18 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0013_auto_20230418_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 16, 56, 36, 793870), verbose_name='date-asked'),
        ),
    ]
