# Generated by Django 3.2.9 on 2023-04-18 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0014_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 16, 57, 39, 796657), verbose_name='date-asked'),
        ),
    ]
