# Generated by Django 3.2.9 on 2023-05-03 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0018_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 15, 51, 23, 915219), verbose_name='date-asked'),
        ),
    ]
