# Generated by Django 3.2.9 on 2023-05-10 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0022_auto_20230508_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 10, 11, 37, 407728), verbose_name='date-asked'),
        ),
    ]
