# Generated by Django 3.2.9 on 2023-05-11 23:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_followers'),
        ('poll', '0025_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 0, 59, 4, 680096), verbose_name='date-asked'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('comment', 'Comment'), ('like', 'Like'), ('vote', 'Vote')], max_length=7)),
                ('action_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_impressions', to='poll.question')),
                ('from_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='users.userprofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.userprofile')),
            ],
        ),
    ]
