# Generated by Django 3.2.9 on 2023-05-12 00:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0026_auto_20230512_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('comment', 'Comment'), ('like', 'Like'), ('vote', 'Vote'), ('follow', 'Follow')], max_length=7),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_receiver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_impressions', to='poll.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 1, 4, 41, 285250), verbose_name='date-asked'),
        ),
    ]
