# Generated by Django 3.2.9 on 2023-05-12 00:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_followers'),
        ('poll', '0028_auto_20230512_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='my_votes', to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_impressions', to='poll.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 1, 23, 54, 525884), verbose_name='date-asked'),
        ),
    ]
