# Generated by Django 3.2.9 on 2023-05-13 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0029_auto_20230512_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('commented on', 'Comment'), ('liked', 'Like'), ('voted on', 'Vote'), ('toggled connect', 'Follow')], max_length=15),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 14, 12, 6, 314984), verbose_name='date-asked'),
        ),
    ]
