# Generated by Django 3.2.9 on 2023-05-13 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0030_auto_20230513_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 14, 25, 52, 861178), verbose_name='date-asked'),
        ),
    ]
