# Generated by Django 3.2.9 on 2023-05-17 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0031_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('comment', 'Comment'), ('like', 'Like'), ('vote', 'Vote'), ('follow', 'Follow')], max_length=15),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 22, 56, 21, 157610), verbose_name='date-asked'),
        ),
    ]
